---
- name: update and upgrade homebrew packages
  homebrew: update_homebrew=yes upgrade_all=yes

- name: install homebrew packages
  homebrew: name={{item}}
  with_items: "{{brew_packages}}"

- name: install homebrew cask packages
  homebrew_cask: name={{item}}
  with_items: "{{cask_packages}}"
